In [1]:
import numpy as np
import torch
import pickle

In [2]:
print("E")

E


In [4]:
!which python

/Users/senxiu/opt/anaconda3/envs/tankbinds/bin/python


In [21]:
data = torch.load("data_batch_0.pt")
affinity_pred = torch.load("affinity_pred_batch_0.pt")
y_pred = torch.load("y_pred_batch_0.pt")

In [48]:
14920

2984.0

In [47]:
data

HeteroDataBatch(
  dis_map=[14920],
  node_xyz=[637, 3],
  coords=[115, 3],
  y=[14920],
  seq=[637],
  affinity=[5],
  compound_pair=[4263, 16],
  compound_pair_batch=[4263],
  compound_pair_ptr=[6],
  pdb=[5],
  group=[5],
  real_affinity_mask=[5],
  real_y_mask=[14920],
  is_equivalent_native_pocket=[5],
  equivalent_native_y_mask=[14920],
  protein={
    node_s=[637, 6],
    node_v=[637, 3, 3],
    batch=[637],
    ptr=[6]
  },
  compound={
    x=[115, 56],
    x_batch=[115],
    x_ptr=[6],
    batch=[115],
    ptr=[6]
  },
  (protein, p2p, protein)={
    edge_index=[2, 14796],
    edge_s=[14796, 32],
    edge_v=[14796, 1, 3]
  },
  (compound, c2c, compound)={
    edge_index=[2, 242],
    edge_weight=[242],
    edge_attr=[242, 19]
  }
)

In [22]:
y_pred.shape, affinity_pred.shape

(torch.Size([14920]), torch.Size([5]))

In [20]:
y = data.y
affinity = data.affinity
dis_map = data.dis_map

y_pred2 = y_pred[data.equivalent_native_y_mask]
dis_map2 = dis_map[data.equivalent_native_y_mask]

IndexError: The shape of the mask [14920] at index 0 does not match the shape of the indexed tensor [3976] at index 0

In [30]:
for i, v in enumerate(data.equivalent_native_y_mask):
    if v.item() == 0 and data.equivalent_native_y_mask[i-1].item() == 1:
        print(i)

1596
14423


In [43]:
list(data.equivalent_native_y_mask)

[tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(True),
 tensor(Tr

In [46]:

with open("asgs.txt", "w") as f:
    f.writelines([str(a.item())+"\n" for a in list(data.equivalent_native_y_mask)])

In [37]:
data.pdb

['3tz2_c', '2ylq_0', '6bee_7', '2y2j', '3t01_2']

In [38]:
import pandas as pd
info = pd.read_csv("info.csv")

In [41]:
info[info.pdb.isin(data.pdb)]

Unnamed: 0 protein_name compound_name     pdb  smiles  affinity  \
23086       23086         2ylq          2ylq  2ylq_0     NaN      4.30   
26763       26763         3t01          3t01  3t01_2     NaN      4.48   
31246       31246         6bee          6bee  6bee_7     NaN      4.66   
34313       34313         2y2j          2y2j    2y2j     NaN      4.80   
45578       45578         3tz2          3tz2  3tz2_c     NaN      5.24   

          uid                                  pocket_com  use_compound_com  \
23086  P10275                 [[26.839  -1.6569 -4.9487]]             False   
26763  Q92UV8                 [[-7.55   40.5067  6.2403]]             False   
31246  P68440              [[121.0583 108.2988 -19.1833]]             False   
34313  Q7CRA4                                         NaN              True   
45578  Q00972  [[  3.67212152 -30.53707123  10.37456036]]             False   

       use_whole_protein  group  has_nci_info  compound_sdf_from_nci  
23086              False  train          True                  False  
26763              False  train          True                  False  
31246              False  train         False                  False  
34313              False  train          True                   True  
45578              False  train         False                  False

In [31]:
115*

HeteroDataBatch(
  dis_map=[14920],
  node_xyz=[637, 3],
  coords=[115, 3],
  y=[14920],
  seq=[637],
  affinity=[5],
  compound_pair=[4263, 16],
  compound_pair_batch=[4263],
  compound_pair_ptr=[6],
  pdb=[5],
  group=[5],
  real_affinity_mask=[5],
  real_y_mask=[14920],
  is_equivalent_native_pocket=[5],
  equivalent_native_y_mask=[14920],
  protein={
    node_s=[637, 6],
    node_v=[637, 3, 3],
    batch=[637],
    ptr=[6]
  },
  compound={
    x=[115, 56],
    x_batch=[115],
    x_ptr=[6],
    batch=[115],
    ptr=[6]
  },
  (protein, p2p, protein)={
    edge_index=[2, 14796],
    edge_s=[14796, 32],
    edge_v=[14796, 1, 3]
  },
  (compound, c2c, compound)={
    edge_index=[2, 242],
    edge_weight=[242],
    edge_attr=[242, 19]
  }
)

In [14]:
y_pred.shape

torch.Size([3976])

In [17]:
data.equivalent_native_y_mask.sum()

tensor(3976)

In [18]:
y_pred[data.equivalent_native_y_mask]

IndexError: The shape of the mask [14920] at index 0 does not match the shape of the indexed tensor [3976] at index 0

In [2]:
import os

len(os.listdir("/home/jovyan/dataspace/NFT/main/nci_protein_ligand_matrix"))

19126

In [ ]:
print("Yes")

In [4]:
import numpy as np


a = np.random.rand(5,3)

In [5]:
a

array([[0.11372235, 0.32982115, 0.63108464],
       [0.08394954, 0.88190771, 0.39837001],
       [0.97127787, 0.31472982, 0.40238377],
       [0.46083623, 0.79557633, 0.37290506],
       [0.59385406, 0.68620738, 0.72175632]])

In [6]:
b = [True, False, False]

In [7]:
a[:, b]

array([[0.11372235],
       [0.08394954],
       [0.97127787],
       [0.46083623],
       [0.59385406]])

In [90]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).reshape(2, -1)
a.shape, a

(torch.Size([2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [91]:
b = torch.tensor([4, 5, 6, 7, 8, 9, 10 ,11]).reshape(2, -1)
b.shape, b

(torch.Size([2, 4]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [88]:
c = torch.einsum("ai,aj->aij", a, b)

In [92]:
c.shape, c

(torch.Size([2, 3, 4]),
 tensor([[[ 4,  5,  6,  7],
          [ 8, 10, 12, 14],
          [12, 15, 18, 21]],
 
         [[32, 36, 40, 44],
          [40, 45, 50, 55],
          [48, 54, 60, 66]]]))

In [81]:
c

tensor([[[[6., 6., 6.],
          [6., 6., 6.],
          [6., 6., 6.]],

         [[6., 6., 6.],
          [6., 6., 6.],
          [6., 6., 6.]]]])

In [115]:
a = torch.tensor([True, True, False, False]).reshape(2,2)

In [121]:
a.shape, a

(torch.Size([2, 2]),
 tensor([[ True,  True],
         [False, False]]))

In [117]:
b = torch.rand(2,2,3)

In [118]:
b.shape, b

(torch.Size([2, 2, 3]),
 tensor([[[0.6007, 0.5474, 0.3965],
          [0.3106, 0.4398, 0.6430]],
 
         [[0.1330, 0.0619, 0.4389],
          [0.7027, 0.4439, 0.8037]]]))

In [112]:
c = torch.tensor([True, False])

In [120]:
b[a].shape

torch.Size([2, 3])